version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idurar-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${PORT:-8888}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_NAME: ${DATABASE_NAME:-idurar}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FILE_UPLOAD_PATH: ./public/uploads
      FILE_UPLOAD_URL: uploads
    ports:
      - "${PORT:-8888}:${PORT:-8888}"
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./public/download:/app/public/download
    networks:
      - idurar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8888}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  idurar-network:
    driver: bridge

volumes:
  uploads:
  downloads:
